In [ ]:
!apt-get update

!apt-get install -y \
libatk1.0-0 \
libatk-bridge2.0-0 \
libcups2 \
libxcomposite1 \
libxdamage1 \
libxfixes3 \
libxrandr2 \
libgbm1 \
libgtk-3-0 \
libasound2t64 \
libnss3

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/ InRelease [3,631 B]
Hit:3 http://archive.ubuntu.com/ubuntu noble InRelease
Get:4 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu noble InRelease [9,161 B]
Get:6 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/ Packages [73.2 kB]
Get:8 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:9 https://r2u.stat.illinois.edu/ubuntu noble/main amd64 Packages [3,015 kB]
Get:10 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [2,159 kB]
Get:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble InRelease [17.8 kB]
Get:12 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [1,268 kB]
Get:13 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1,620 kB]
Get:14 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [2,025 kB]
Get:15 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [36.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu noble-backports/main amd64 Packages [49.0 kB]
Get:17 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble/main amd64 Packages [52.1 kB]
Get:18 https://r2u.stat.illinois.edu/ubuntu noble/main all Packages [10.2 MB]
Get:19 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [1,544 kB]
Get:20 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [1,858 kB]
Fetched 24.3 MB in 2s (13.2 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libatk1.0-0t64' instead of 'libatk1.0-0'
Note, selecting 'libatk-bridge2.0-0t64' instead of 'libatk-bridge2.0-0'
Note, selecting 'libcups2t64' instead of 'libcups2'
Note, selecting 'libgtk-3-0t64' instead of 'libgtk-3-0'
libcups2t64 is already the newest version (2.4.7-1.2ubuntu7.14).
libcups2t64 set to manually installed.
libxdamage1 is already the newest version (1:1.1.6-1build1).
libxdamage1 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-2build1).
libxfixes3 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-2build1).
libxrandr2 set to manually installed.
libgbm1 is already the newest version (25.2.8-0ubuntu0.24.04.2).
libgbm1 set to manually installed.
libasound2t64 is already the newest version (1.2.11-1ubuntu0.3).
libasound2t64 set to manually installed.
libnss3 is already the newest version (2:3.98-1ubuntu0.2).
libnss3 set to manually installed.
The following additional packages will be installed:
  at-spi2-common at-spi2-core gsettings-desktop-schemas libatspi2.0-0t64
  libgtk-3-bin libgtk-3-common librsvg2-common libxtst6 session-migration
Suggested packages:
  gvfs
The following NEW packages will be installed:
  at-spi2-common at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0t64
  libatk1.0-0t64 libatspi2.0-0t64 libgtk-3-0t64 libgtk-3-bin libgtk-3-common
  librsvg2-common libxcomposite1 libxtst6 session-migration
0 upgraded, 13 newly installed, 0 to remove and 26 not upgraded.
Need to get 4,756 kB of archives.
After this operation, 16.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 at-spi2-common all 2.52.0-1build1 [8,674 B]
Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 libatspi2.0-0t64 amd64 2.52.0-1build1 [80.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble/main amd64 libxtst6 amd64 2:1.2.3-1.1build1 [12.6 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 session-migration amd64 0.3.9build1 [9,034 B]
Get:5 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 gsettings-desktop-schemas all 46.1-0ubuntu1 [35.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 at-spi2-core amd64 2.52.0-1build1 [56.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble/main amd64 libatk1.0-0t64 amd64 2.52.0-1build1 [55.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu noble/main amd64 libatk-bridge2.0-0t64 amd64 2.52.0-1build1 [66.0 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble/main amd64 libxcomposite1 amd64 1:0.4.5-1build3 [6,320 B]
Get:10 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk-3-common all 3.24.41-4ubuntu1.3 [1,426 kB]
Get:11 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk-3-0t64 amd64 3.24.41-4ubuntu1.3 [2,913 kB]
Get:12 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk-3-bin amd64 3.24.41-4ubuntu1.3 [73.9 kB]
Get:13 http://archive.ubuntu.com/ubuntu noble/main amd64 librsvg2-common amd64 2.58.0+dfsg-1build1 [11.8 kB]
Fetched 4,756 kB in 1s (9,060 kB/s)
Selecting previously unselected package at-spi2-common.
(Reading database ... 122809 files and directories currently installed.)
Preparing to unpack .../00-at-spi2-common_2.52.0-1build1_all.deb ...
Unpacking at-spi2-common (2.52.0-1build1) ...
Selecting previously unselected package libatspi2.0-0t64:amd64.
Preparing to unpack .../01-libatspi2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../02-libxtst6_2%3a1.2.3-1.1build1_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1.1build1) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../03-session-migration_0.3.9build1_amd64.deb ...
Unpacking session-migration (0.3.9build1) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../04-gsettings-desktop-schemas_46.1-0ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (46.1-0ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../05-at-spi2-core_2.52.0-1build1_amd64.deb ...
Unpacking at-spi2-core (2.52.0-1build1) ...
Selecting previously unselected package libatk1.0-0t64:amd64.
Preparing to unpack .../06-libatk1.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatk-bridge2.0-0t64:amd64.
Preparing to unpack .../07-libatk-bridge2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../08-libxcomposite1_1%3a0.4.5-1build3_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build3) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../09-libgtk-3-common_3.24.41-4ubuntu1.3_all.deb ...
Unpacking libgtk-3-common (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package libgtk-3-0t64:amd64.
Preparing to unpack .../10-libgtk-3-0t64_3.24.41-4ubuntu1.3_amd64.deb ...
Unpacking libgtk-3-0t64:amd64 (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../11-libgtk-3-bin_3.24.41-4ubuntu1.3_amd64.deb ...
Unpacking libgtk-3-bin (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../12-librsvg2-common_2.58.0+dfsg-1build1_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.58.0+dfsg-1build1) ...
Setting up session-migration (0.3.9build1) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1.1build1) ...
Setting up libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up librsvg2-common:amd64 (2.58.0+dfsg-1build1) ...
Setting up at-spi2-common (2.52.0-1build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build3) ...
Setting up libgtk-3-common (3.24.41-4ubuntu1.3) ...
Setting up gsettings-desktop-schemas (46.1-0ubuntu1) ...
Setting up libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Setting up libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.10+dfsg-3ubuntu3.3) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.8) ...
Setting up libgtk-3-0t64:amd64 (3.24.41-4ubuntu1.3) ...
Setting up at-spi2-core (2.52.0-1build1) ...
Setting up libgtk-3-bin (3.24.41-4ubuntu1.3) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

In [ ]:
!pip install playwright

!playwright install chromium

Requirement already satisfied: playwright in /usr/local/lib/python3.13/dist-packages (1.63.0)
Requirement already satisfied: pyee<14,>=13 in /usr/local/lib/python3.13/dist-packages (from playwright) (13.0.1)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.13/dist-packages (from playwright) (3.5.5)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from pyee<14,>=13->playwright) (4.16.0)

In [ ]:
from playwright.async_api import async_playwright
import asyncio
import nest_asyncio

nest_asyncio.apply()


async def test():

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-dev-shm-usage"
            ]
        )

        page = await browser.new_page()

        await page.goto(
            "https://www.google.com"
        )

        print(
            await page.title()
        )

        await browser.close()


asyncio.get_event_loop().run_until_complete(test())

Google

In [ ]:
import asyncio
import nest_asyncio

nest_asyncio.apply()


async def cek_api():

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-dev-shm-usage"
            ]
        )


        page = await browser.new_page()


        def lihat_request(req):

            url=req.url

            if (
                "api" in url.lower()
                or
                "book" in url.lower()
                or
                "catalog" in url.lower()
            ):

                print(
                    "REQUEST:",
                    url
                )


        page.on(
            "request",
            lihat_request
        )


        await page.goto(
            "https://buku.kemendikdasmen.go.id/katalog/buku-kurikulum-merdeka",
            wait_until="networkidle"
        )


        await page.wait_for_timeout(
            5000
        )


        await page.click(
            "#checkSD"
        )


        await page.wait_for_timeout(
            5000
        )


        await browser.close()



asyncio.get_event_loop().run_until_complete(
    cek_api()
)

REQUEST: https://www.google-analytics.com/g/collect?v=2&tid=G-CY595V9CN2&gtm=45je69l1v9230121440za208zd9230121440xf1&_p=1790171817022&gcd=13l3l3l3l1l1&npa=0&dma=0&cid=1070144861.1790171818&frm=0&ngs=1&pscdl=noapi&rcb=14&sr=1280x720&uaa=x86&uab=64&uafvl=HeadlessChrome%3B153.0.8010.12%7CNot_A%2520Brand%3B8.0.0.0%7CChromium%3B153.0.8010.12&uam=&uamb=0&uap=Linux&uapv=&uaw=0&ul=en-us&_s=1&tag_exp=115616986~115938466~115938469~118012007~118897920~118897930~120213116~120385423~120469145~120469153~121280971&sid=1790171817&sct=1&seg=0&dl=https%3A%2F%2Fbuku.kemendikdasmen.go.id%2Fkatalog%2Fbuku-kurikulum-merdeka&dt=SIBI%20-%20Sistem%20Informasi%20Perbukuan%20Indonesia&en=page_view&_fv=1&_nsi=1&_ss=1&_ee=1&tfd=1506
REQUEST: https://www.google-analytics.com/g/collect?v=2&tid=G-KQZ4PELP78&gtm=45je69l1v869537125za208zb9230121440zd9230121440xf1&_p=1790171817022&gcd=13l3l3l3l1l1&npa=0&dma=0&cid=1070144861.1790171818&frm=0&ngs=1&pscdl=noapi&rcb=1&sr=1280x720&uaa=x86&uab=64&uafvl=HeadlessChrome%3B153.0.8010.12%7CNot_A%2520Brand%3B8.0.0.0%7CChromium%3B153.0.8010.12&uam=&uamb=0&uap=Linux&uapv=&uaw=0&ul=en-us&_s=1&tag_exp=115938466~115938468~118897920~118897930~120213116~120385423~120469145~120469153~121280971&sid=1790171817&sct=1&seg=0&dl=https%3A%2F%2Fbuku.kemendikdasmen.go.id%2Fkatalog%2Fbuku-kurikulum-merdeka&dt=SIBI%20-%20Sistem%20Informasi%20Perbukuan%20Indonesia&en=page_view&_fv=1&_ss=1&_ee=1&tfd=1743
REQUEST: https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;800&Neuton:ital,wght@0,200;0,300;0,400;0,700;0,800;1,400&display=swap
REQUEST: https://api.buku.cloudapp.web.id/api/catalogue/search
REQUEST: https://api.buku.cloudapp.web.id/api/catalogue/getPenggerakTextBooks?limit=2000&type_pdf&order_by=updated_at
REQUEST: https://buku.kemendikdasmen.go.id/assets/image/catalog/bg-hero.png
REQUEST: https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.pt_BR.l4Bv_WkVC6g.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCOuH5S2uqmF6E8zOW7n3yiqiwhzNQ/cb=gapi.loaded_0
REQUEST: https://buku.kemendikdasmen.go.id/assets/image/catalog/not-found.png
REQUEST: https://www.google-analytics.com/g/collect?v=2&tid=G-CY595V9CN2&gtm=45je69l1v9230121440za200zd9230121440xf1&_p=1790171817022&gcd=13l3l3l3l1l1&npa=0&dma=0&_eu=AEAAAAQ&ae=a&cid=1070144861.1790171818&frm=0&ngs=1&pscdl=noapi&rcb=14&sr=1280x720&uaa=x86&uab=64&uafvl=HeadlessChrome%3B153.0.8010.12%7CNot_A%2520Brand%3B8.0.0.0%7CChromium%3B153.0.8010.12&uam=&uamb=0&uap=Linux&uapv=&uaw=0&ul=en-us&_s=2&tag_exp=115616986~115938466~115938469~118012007~118897920~118897930~120213116~120385423~120469145~120469153~121280971&sid=1790171817&sct=1&seg=0&dl=https%3A%2F%2Fbuku.kemendikdasmen.go.id%2Fkatalog%2Fbuku-kurikulum-merdeka&dt=SIBI%20-%20Sistem%20Informasi%20Perbukuan%20Indonesia&en=scroll&epn.percent_scrolled=90&_et=17&tfd=6539
REQUEST: https://www.google-analytics.com/g/collect?v=2&tid=G-KQZ4PELP78&gtm=45je69l1v869537125za200zb9230121440zd9230121440xf1&_p=1790171817022&gcd=13l3l3l3l1l1&npa=0&dma=0&_eu=AEAAAAQ&ae=a&cid=1070144861.1790171818&frm=0&ngs=1&pscdl=noapi&rcb=1&sr=1280x720&uaa=x86&uab=64&uafvl=HeadlessChrome%3B153.0.8010.12%7CNot_A%2520Brand%3B8.0.0.0%7CChromium%3B153.0.8010.12&uam=&uamb=0&uap=Linux&uapv=&uaw=0&ul=en-us&_s=2&tag_exp=115938466~115938468~118897920~118897930~120213116~120385423~120469145~120469153~121280971&sid=1790171817&sct=1&seg=0&dl=https%3A%2F%2Fbuku.kemendikdasmen.go.id%2Fkatalog%2Fbuku-kurikulum-merdeka&dt=SIBI%20-%20Sistem%20Informasi%20Perbukuan%20Indonesia&en=scroll&epn.percent_scrolled=90&_et=28&tfd=6781
REQUEST: https://api.buku.cloudapp.web.id/api/catalogue/getPenggerakTextBooks?limit=2000&type_pdf&order_by=updated_at&level_sd

In [ ]:
import requests
import json
import pandas as pd


API = "https://api.buku.cloudapp.web.id/api/catalogue/getPenggerakTextBooks?limit=2000&type_pdf&order_by=updated_at&level_sd"


response = requests.get(
    API,
    timeout=60
)


print(
    response.status_code
)


data = response.json()


print(
    type(data)
)

200
<class 'dict'>

In [ ]:
data.keys()

dict_keys(['status', 'results', 'totalSize'])

In [ ]:
print(json.dumps(data, indent=2)[:3000])

{
  "status": "success",
  "results": [
    {
      "id": "2481",
      "het_id": "2825",
      "title": "Buku Panduan Guru Pendidikan Jasmani, Olahraga, dan Kesehatan untuk SD/MI Kelas VI",
      "slug": "buku-panduan-guru-pendidikan-jasmani-olahraga-dan-kesehatan-untuk-sdmi-kelas-vi",
      "image": "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/PJOK_BG_KLS_VI_Cover.PNG",
      "attachment": "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/PJOK_BG_KLS_VI_.pdf",
      "description": "",
      "published_year": "0000-00-00",
      "class": "6",
      "level": "SD/MI",
      "writer": "Tri Agus Prasetijo, Alda Indrawan",
      "reviewer": "Advendi Kristiyandaru, Johan Irmansyah",
      "translator": "",
      "adapter": "Supriyatno, Maharani Prananingrum, Ervina, Putri Ainur Islam",
      "designer": "Ingrid Pangestu",
      "cover_designer": "",
      "ilustrator": "Khairin Nisa",
      "editor": "Mely Rizki Suryanita, Ervina, Maretta Gunawan",
      "aligner": "Supriyatno, Lenny Puspita Ekawaty, NPM Yuliarti Dewi, Arifah Dinda Lestari",
      "publisher": "Pusat Perbukuan",
      "contributor": null,
      "language": "Indonesia",
      "context": "",
      "subject": "pjok",
      "format": "Text",
      "isbn": "978-634-00-3177-5",
      "curriculum": "2022",
      "collation": "",
      "type": "pdf",
      "edition": "1",
      "unit": "Pusat  Perbukuan",
      "status": "publish",
      "category": "buku_sekolah_penggerak",
      "book_type": "buku_siswa",
      "version": null,
      "price_zone_1": "0",
      "price_zone_2": "0",
      "price_zone_3": "0",
      "price_zone_4": "0",
      "price_zone_5A": "0",
      "price_zone_5B": "0",
      "created_at": "2023-07-30 02:29:05",
      "updated_at": "2026-07-16 14:22:30",
      "deleted_at": null
    },
    {
      "id": "3261",
      "het_id": "4024",
      "title": "Bahasa Indonesia Lihat Sekitar untuk SD/MI Kelas IV (Edisi Revisi)",
      "slug": "bahasa-indonesia-lihat-sekitar-untuk-sdmi-kelas-iv-edisi-revisi",
      "image": "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Bahasa_Indonesia_BS_KLS_IV_Rev_Cover.png",
      "attachment": "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Bahasa_Indonesia_BS_KLS_IV_Rev.pdf",
      "description": "",
      "published_year": "2024-01-01",
      "class": "4",
      "level": "SD/MI",
      "writer": "Eva Yulia Nukman, Cicilia Erni Setyowati ",
      "reviewer": "-",
      "translator": "",
      "adapter": "",
      "designer": "Suhardiman",
      "cover_designer": "",
      "ilustrator": "Siti Wardiyah, Felia Febriany Gunawan, Kyara Letta, Elvira Novianti Ken, Nabila Adani, Dewi Tri Kusumah Handayani, Ratna Kusuma Halim, Dian Her Dwiandaru Rm ",
      "editor": "Flora Maharani, Evi Shelvia, Siti Wardiyah ",
      "aligner": "Supriyatno, Lenny Puspita Ekawaty, Sofia Nida Khoerunnisa",
      "publisher": "Pusat Kurikulum dan Perbukuan",
      "contribu

In [ ]:
books = data["results"]

print(
    "Jumlah buku:",
    len(books)
)

Jumlah buku: 174

In [ ]:
import pandas as pd


final_books = []


for b in books:

    title = b.get("title","").lower()


    # deteksi jenis buku

    if (
        "guru" in title
        or
        "panduan guru" in title
    ):
        jenis = "Guru"

    else:
        jenis = "Siswa"



    final_books.append({

        "id": b.get("id"),

        "judul": b.get("title"),

        "jenis": jenis,

        "kelas": b.get("class"),

        "mata_pelajaran": b.get("subject"),

        "level": b.get("level"),

        "isbn": b.get("isbn"),

        "penulis": b.get("writer"),

        "penerbit": b.get("publisher"),

        "cover": b.get("image"),

        "link_pdf": b.get("attachment"),

        "slug": b.get("slug")

    })


df = pd.DataFrame(final_books)


print(
    df.shape
)


df.head()

(174, 12)

,id,judul,jenis,kelas,mata_pelajaran,level,isbn,penulis,penerbit,cover,link_pdf,slug
0,2481,"Buku Panduan Guru Pendidikan Jasmani, Olahraga...",Guru,6,pjok,SD/MI,978-634-00-3177-5,"Tri Agus Prasetijo, Alda Indrawan",Pusat Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,buku-panduan-guru-pendidikan-jasmani-olahraga-...
1,3261,Bahasa Indonesia Lihat Sekitar untuk SD/MI Kel...,Siswa,4,bahasa_indonesia,SD/MI,978-623-118-363-7,"Eva Yulia Nukman, Cicilia Erni Setyowati",Pusat Kurikulum dan Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,bahasa-indonesia-lihat-sekitar-untuk-sdmi-kela...
2,3942,Bahasa Indonesia: Kawan Seiring untuk SD/MI Ke...,Siswa,3,bahasa_indonesia,SD/MI,978-634-00-3315-1,"Gantino Habibi, S. Nailul Muna Aljamaliah",Pusat Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,bahasa-indonesia-kawan-seiring-untuk-sdmi-kela...
3,3916,Panduan Guru Bahasa Indonesia: Anak-Anak yang ...,Guru,6,bahasa_indonesia,SD/MI,978-634-00-2484-5,"Nisa Yustisia, Darwanto, M. Arif",Pusat Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,panduan-guru-bahasa-indonesia-anak-anak-yang-m...
4,3257,Bahasa Indonesia Aku Bisa! untuk SD/MI Kelas I...,Siswa,1,bahasa_indonesia,SD/MI,978-623-118-362-0,Sofie Dewayani,Pusat Kurikulum dan Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,bahasa-indonesia-aku-bisa-untuk-sd-mi-kelas-i-...

In [ ]:
import pandas as pd


final_books = []


for b in books:


    if b.get("book_type") == "buku_guru":

        jenis = "Guru"

    elif b.get("book_type") == "buku_siswa":

        jenis = "Siswa"

    else:

        jenis = b.get("book_type")



    final_books.append({

        "id":
        b.get("id"),


        "judul":
        b.get("title"),


        "jenis":
        jenis,


        "kelas":
        b.get("class"),


        "mata_pelajaran":
        b.get("subject"),


        "level":
        b.get("level"),


        "isbn":
        b.get("isbn"),


        "penulis":
        b.get("writer"),


        "penerbit":
        b.get("publisher"),


        "cover":
        b.get("image"),


        "link_pdf":
        b.get("attachment"),


        "slug":
        b.get("slug")

    })



df = pd.DataFrame(
    final_books
)


print(df.shape)

df.head()

(174, 12)

,id,judul,jenis,kelas,mata_pelajaran,level,isbn,penulis,penerbit,cover,link_pdf,slug
0,2481,"Buku Panduan Guru Pendidikan Jasmani, Olahraga...",Siswa,6,pjok,SD/MI,978-634-00-3177-5,"Tri Agus Prasetijo, Alda Indrawan",Pusat Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,buku-panduan-guru-pendidikan-jasmani-olahraga-...
1,3261,Bahasa Indonesia Lihat Sekitar untuk SD/MI Kel...,Siswa,4,bahasa_indonesia,SD/MI,978-623-118-363-7,"Eva Yulia Nukman, Cicilia Erni Setyowati",Pusat Kurikulum dan Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,bahasa-indonesia-lihat-sekitar-untuk-sdmi-kela...
2,3942,Bahasa Indonesia: Kawan Seiring untuk SD/MI Ke...,Siswa,3,bahasa_indonesia,SD/MI,978-634-00-3315-1,"Gantino Habibi, S. Nailul Muna Aljamaliah",Pusat Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,bahasa-indonesia-kawan-seiring-untuk-sdmi-kela...
3,3916,Panduan Guru Bahasa Indonesia: Anak-Anak yang ...,Guru,6,bahasa_indonesia,SD/MI,978-634-00-2484-5,"Nisa Yustisia, Darwanto, M. Arif",Pusat Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,panduan-guru-bahasa-indonesia-anak-anak-yang-m...
4,3257,Bahasa Indonesia Aku Bisa! untuk SD/MI Kelas I...,Siswa,1,bahasa_indonesia,SD/MI,978-623-118-362-0,Sofie Dewayani,Pusat Kurikulum dan Perbukuan,https://static-sc.cloudapp.web.id/content/imag...,https://static-sc.cloudapp.web.id/content/pdf/...,bahasa-indonesia-aku-bisa-untuk-sd-mi-kelas-i-...

In [ ]:
df["jenis"].value_counts()

jenis
Guru        62
Siswa       58
Buku PDF    54
Name: count, dtype: int64

In [ ]:
from collections import Counter

Counter(
    [
        b.get("book_type")
        for b in books
    ]
)

Counter({'buku_siswa': 58, 'buku_guru': 62, 'Buku PDF': 54})

In [ ]:
pdf_unknown = [
    b for b in books
    if b.get("book_type") == "Buku PDF"
]


print(len(pdf_unknown))


for b in pdf_unknown[:20]:
    print(
        b["title"],
        "|",
        b.get("class"),
        "|",
        b.get("subject")
    )

54
Buku Panduan Guru Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas I | 1 | agama_buddha
Buku Panduan Guru Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas I | 1 | agama_hindu
Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas I | 1 | agama_hindu
Buku Panduan Guru Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas I | 1 | agama_katolik
Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas I | 1 | agama_katolik
Buku Panduan Guru Pendidikan Agama Konghucu dan Budi Pekerti untuk SD Kelas I | 1 | agama_khonghucu
Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas I | 1 | agama_khonghucu
Buku Panduan Guru Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas I | 1 | agama_kristen
Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas I | 1 | agama_kristen
Buku Panduan Guru Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas IV | 4 | agama_buddha
Buku Panduan Guru Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas IV | 4 | agama_hindu
Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas IV | 4 | agama_hindu
Buku Panduan Guru Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas IV | 4 | agama_islam
Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas IV | 4 | agama_islam
Buku Panduan Guru Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas IV | 4 | agama_katolik
Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas IV | 4 | agama_katolik
Buku Panduan Guru Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas IV | 4 | agama_khonghucu
Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas IV | 4 | agama_khonghucu
Buku Panduan Guru Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas IV | 4 | agama_kristen
Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas IV | 4 | agama_kristen

In [ ]:
def kategori_buku(b):

    title = str(
        b.get("title","")
    ).lower()


    # Guru

    if (
        "panduan guru" in title
        or
        "buku panduan guru" in title
    ):
        return "Guru"


    # selain panduan guru dianggap siswa

    return "Siswa"

In [ ]:
def kategori_buku(b):

    book_type = str(
        b.get("book_type","")
    ).lower()


    title = str(
        b.get("title","")
    ).lower()



    # data API yang sudah jelas

    if book_type == "buku_guru":
        return "Guru"


    if book_type == "buku_siswa":
        return "Siswa"



    # khusus Buku PDF

    if (
        "panduan guru" in title
        or
        "buku panduan guru" in title
    ):
        return "Guru"


    return "Siswa"

In [ ]:
final_books=[]


for b in books:

    final_books.append({

        "id": b.get("id"),

        "judul": b.get("title"),

        "jenis": kategori_buku(b),

        "kelas": b.get("class"),

        "mata_pelajaran": b.get("subject"),

        "isbn": b.get("isbn"),

        "link_pdf": b.get("attachment"),

        "cover": b.get("image"),

        "slug": b.get("slug")

    })


df = pd.DataFrame(final_books)


df["jenis"].value_counts()

jenis
Guru     90
Siswa    84
Name: count, dtype: int64

In [ ]:
def kategori_buku(b):

    book_type = str(
        b.get("book_type","")
    ).lower()


    title = str(
        b.get("title","")
    ).lower()



    # =====================
    # DATA API LANGSUNG
    # =====================

    if book_type == "buku_guru":
        return "Guru"


    if book_type == "buku_siswa":
        return "Siswa"



    # =====================
    # KHUSUS Buku PDF
    # =====================

    guru_keywords = [
        "panduan guru",
        "buku panduan guru"
    ]


    for keyword in guru_keywords:

        if keyword in title:
            return "Guru"



    return "Siswa"

In [ ]:
final_books=[]


for b in books:

    final_books.append({

        "id": b.get("id"),

        "judul": b.get("title"),

        "jenis": kategori_buku(b),

        "kelas": b.get("class"),

        "mapel": b.get("subject"),

        "isbn": b.get("isbn"),

        "link_pdf": b.get("attachment"),

        "cover": b.get("image"),

        "slug": b.get("slug")

    })


df = pd.DataFrame(final_books)


df["jenis"].value_counts()

jenis
Guru     90
Siswa    84
Name: count, dtype: int64

In [ ]:
pdf_books = [
    b for b in books
    if b.get("book_type") == "Buku PDF"
]


print("Jumlah Buku PDF:", len(pdf_books))


for b in pdf_books:

    print(
        b["title"]
    )

Jumlah Buku PDF: 54
Buku Panduan Guru Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas I
Buku Panduan Guru Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas I
Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas I
Buku Panduan Guru Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas I
Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas I
Buku Panduan Guru Pendidikan Agama Konghucu dan Budi Pekerti untuk SD Kelas I
Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas I
Buku Panduan Guru Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas I
Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas I
Buku Panduan Guru Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas IV
Buku Panduan Guru Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas IV
Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas IV
Buku Panduan Guru Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas IV
Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas IV
Buku Panduan Guru Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas IV
Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas IV
Buku Panduan Guru Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas IV
Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas IV
Buku Panduan Guru Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas IV
Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas IV
Buku Panduan Guru Pendidikan Kepercayaan Terhadap Tuhan Yang Maha Esa dan Budi Pekerti untuk SD Kelas IV
Pendidikan Kepercayaan Terhadap Tuhan Yang Maha Esa dan Budi Pekerti untuk SD Kelas IV
Buku Panduan Guru Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas II
Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas II
Buku Panduan Guru Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas II
Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas II
Buku Panduan Guru Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas II
Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas II
Buku Panduan Guru Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas II
Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas II
Buku Panduan Guru Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas II
Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas II
Buku Panduan Guru Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas II
Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas II
Buku Panduan Guru Pendidikan Kepercayaan Terhadap Tuhan Yang Maha Esa dan Budi Pekerti untuk SD Kelas II
Pendidikan Kepercayaan Terhadap Tuhan Yang Maha Esa dan Budi Pekerti untuk SD Kelas II
Buku Panduan Guru Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas V
Pendidikan Agama Buddha dan Budi Pekerti untuk SD Kelas V
Buku Panduan Guru Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas V
Pendidikan Agama Hindu dan Budi Pekerti untuk SD Kelas V
Buku Panduan Guru Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas V
Pendidikan Agama Islam dan Budi Pekerti untuk SD Kelas V
Buku Panduan Guru Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas V
Pendidikan Agama Katolik dan Budi Pekerti untuk SD Kelas V
Buku Panduan Guru Pendidikan Kepercayaan Terhadap Tuhan Yang Maha Esa dan Budi Pekerti untuk SD Kelas V
Pendidikan Kepercayaan Terhadap Tuhan Yang Maha Esa dan Budi Pekerti untuk SD Kelas V
Buku Panduan Guru Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas V
Pendidikan Agama Kristen dan Budi Pekerti untuk SD Kelas V
Buku Panduan Guru Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas V
Pendidikan Agama Khonghucu dan Budi Pekerti untuk SD Kelas V
Buku Panduan Guru Matematika untuk SD/MI Kelas II
Buku Panduan Guru Matematika untuk SD/MI Kelas V
Matematika untuk SD/MI Kelas II
Matematika untuk SD/MI Kelas V

In [ ]:
def kategori_buku(b):

    book_type = str(
        b.get("book_type","")
    ).lower()

    title = str(
        b.get("title","")
    ).lower()


    # data API yang sudah pasti

    if book_type == "buku_guru":
        return "Guru"


    if book_type == "buku_siswa":
        return "Siswa"



    # khusus Buku PDF

    if title.startswith(
        "buku panduan guru"
    ):
        return "Guru"


    return "Siswa"

In [ ]:
final_books=[]


for b in books:

    final_books.append({

        "id":
        b.get("id"),

        "judul":
        b.get("title"),

        "jenis":
        kategori_buku(b),

        "kelas":
        b.get("class"),

        "mata_pelajaran":
        b.get("subject"),

        "isbn":
        b.get("isbn"),

        "penulis":
        b.get("writer"),

        "penerbit":
        b.get("publisher"),

        "cover":
        b.get("image"),

        "link_pdf":
        b.get("attachment"),

        "slug":
        b.get("slug")

    })


df = pd.DataFrame(final_books)


df["jenis"].value_counts()

jenis
Guru     90
Siswa    84
Name: count, dtype: int64

In [ ]:
# export CSV final

df.to_csv(
    "database_buku_sd_mi_final.csv",
    index=False,
    encoding="utf-8-sig"
)


# export JSON final

import json

with open(
    "database_buku_sd_mi_final.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        final_books,
        f,
        ensure_ascii=False,
        indent=4
    )


print("Export selesai")

Export selesai

In [ ]:
!apt-get update -qq
!apt-get install -y ghostscript
!pip install tqdm

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  fonts-droid-fallback fonts-noto-mono fonts-urw-base35 libgs-common libgs10
  libgs10-common libidn12 libijs-0.35 libjbig2dec0 poppler-data
  xfonts-encodings xfonts-utils
Suggested packages:
  fonts-noto fonts-freefont-otf | fonts-freefont-ttf fonts-texgyre
  texlive-binaries poppler-utils fonts-japanese-mincho | fonts-ipafont-mincho
  fonts-japanese-gothic | fonts-ipafont-gothic fonts-arphic-ukai
  fonts-arphic-uming fonts-nanum
The following NEW packages will be installed:
  fonts-droid-fallback fonts-noto-mono fonts-urw-base35 ghostscript
  libgs-common libgs10 libgs10-common libidn12 libijs-0.35 libjbig2dec0
  poppler-data xfonts-encodings xfonts-utils
0 upgraded, 13 newly installed, 0 to remove and 26 not upgraded.
Need to get 20.7 MB of archives.
After this operation, 67.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 fonts-droid-fallback all 1:6.0.1r16-1.1build1 [1,805 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 poppler-data all 0.4.12-1 [2,060 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble/main amd64 fonts-noto-mono all 20201225-2 [435 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 xfonts-encodings all 1:1.0.5-0ubuntu2 [578 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 xfonts-utils amd64 1:7.7+6build3 [94.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 fonts-urw-base35 all 20200910-8 [11.0 MB]
Get:7 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgs-common all 10.02.1~dfsg1-0ubuntu7.9 [176 kB]
Get:8 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgs10-common all 10.02.1~dfsg1-0ubuntu7.9 [488 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libidn12 amd64 1.42-1ubuntu0.1 [56.1 kB]
Get:10 http://archive.ubuntu.com/ubuntu noble/main amd64 libijs-0.35 amd64 0.35-15.1build1 [15.3 kB]
Get:11 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libjbig2dec0 amd64 0.20-1ubuntu0.24.04.1 [65.2 kB]
Get:12 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgs10 amd64 10.02.1~dfsg1-0ubuntu7.9 [3,898 kB]
Get:13 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 ghostscript amd64 10.02.1~dfsg1-0ubuntu7.9 [43.4 kB]
Fetched 20.7 MB in 1s (26.7 MB/s)
Selecting previously unselected package fonts-droid-fallback.
(Reading database ... 123020 files and directories currently installed.)
Preparing to unpack .../00-fonts-droid-fallback_1%3a6.0.1r16-1.1build1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1build1) ...
Selecting previously unselected package poppler-data.
Preparing to unpack .../01-poppler-data_0.4.12-1_all.deb ...
Unpacking poppler-data (0.4.12-1) ...
Selecting previously unselected package fonts-noto-mono.
Preparing to unpack .../02-fonts-noto-mono_20201225-2_all.deb ...
Unpacking fonts-noto-mono (20201225-2) ...
Selecting previously unselected package xfonts-encodings.
Preparing to unpack .../03-xfonts-encodings_1%3a1.0.5-0ubuntu2_all.deb ...
Unpacking xfonts-encodings (1:1.0.5-0ubuntu2) ...
Selecting previously unselected package xfonts-utils.
Preparing to unpack .../04-xfonts-utils_1%3a7.7+6build3_amd64.deb ...
Unpacking xfonts-utils (1:7.7+6build3) ...
Selecting previously unselected package fonts-urw-base35.
Preparing to unpack .../05-fonts-urw-base35_20200910-8_all.deb ...
Unpacking fonts-urw-base35 (20200910-8) ...
Selecting previously unselected package libgs-common.
Preparing to unpack .../06-libgs-common_10.02.1~dfsg1-0ubuntu7.9_all.deb ...
Unpacking libgs-common (10.02.1~dfsg1-0ubuntu7.9) ...
Selecting previously unselected package libgs10-common.
Preparing to unpack .../07-libgs10-common_10.02.1~dfsg1-0ubuntu7.9_all.deb ...
Unpacking libgs10-common (10.02.1~dfsg1-0ubuntu7.9) ...
Selecting previously unselected package libidn12:amd64.
Preparing to unpack .../08-libidn12_1.42-1ubuntu0.1_amd64.deb ...
Unpacking libidn12:amd64 (1.42-1ubuntu0.1) ...
Selecting previously unselected package libijs-0.35:amd64.
Preparing to unpack .../09-libijs-0.35_0.35-15.1build1_amd64.deb ...
Unpacking libijs-0.35:amd64 (0.35-15.1build1) ...
Selecting previously unselected package libjbig2dec0:amd64.
Preparing to unpack .../10-libjbig2dec0_0.20-1ubuntu0.24.04.1_amd64.deb ...
Unpacking libjbig2dec0:amd64 (0.20-1ubuntu0.24.04.1) ...
Selecting previously unselected package libgs10:amd64.
Preparing to unpack .../11-libgs10_10.02.1~dfsg1-0ubuntu7.9_amd64.deb ...
Unpacking libgs10:amd64 (10.02.1~dfsg1-0ubuntu7.9) ...
Selecting previously unselected package ghostscript.
Preparing to unpack .../12-ghostscript_10.02.1~dfsg1-0ubuntu7.9_amd64.deb ...
Unpacking ghostscript (10.02.1~dfsg1-0ubuntu7.9) ...
Setting up fonts-noto-mono (20201225-2) ...
Setting up libijs-0.35:amd64 (0.35-15.1build1) ...
Setting up libgs-common (10.02.1~dfsg1-0ubuntu7.9) ...
Setting up poppler-data (0.4.12-1) ...
Setting up libjbig2dec0:amd64 (0.20-1ubuntu0.24.04.1) ...
Setting up xfonts-encodings (1:1.0.5-0ubuntu2) ...
Setting up libidn12:amd64 (1.42-1ubuntu0.1) ...
Setting up fonts-droid-fallback (1:6.0.1r16-1.1build1) ...
Setting up xfonts-utils (1:7.7+6build3) ...
Setting up fonts-urw-base35 (20200910-8) ...
Setting up libgs10-common (10.02.1~dfsg1-0ubuntu7.9) ...
Setting up libgs10:amd64 (10.02.1~dfsg1-0ubuntu7.9) ...
Setting up ghostscript (10.02.1~dfsg1-0ubuntu7.9) ...
Processing triggers for fontconfig (2.15.0-1.1ubuntu2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (4.67.3)

In [ ]:
import os

BASE_FOLDER = "Buku_SD_MI"

for jenis in ["Guru", "Siswa"]:
    for kelas in range(1,7):
        os.makedirs(
            f"{BASE_FOLDER}/{jenis}/Kelas {kelas}",
            exist_ok=True
        )

print("Folder siap")

Folder siap

In [ ]:
import requests
import os
import re

from tqdm.auto import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


BASE_FOLDER = "Buku_SD_MI"


def clean_filename(name):

    name = re.sub(
        r'[\\/*?:"<>|]',
        "",
        name
    )

    return name.strip()



def download_file(row):

    jenis = row["jenis"]
    kelas = row["kelas"]


    folder = (
        f"{BASE_FOLDER}/"
        f"{jenis}/"
        f"Kelas {kelas}"
    )


    os.makedirs(
        folder,
        exist_ok=True
    )


    filename = clean_filename(
        row["judul"]
    ) + ".pdf"


    filepath = os.path.join(
        folder,
        filename
    )


    # skip jika sudah ada

    if os.path.exists(filepath):

        return "skip"



    try:

        r = requests.get(
            row["link_pdf"],
            timeout=120
        )


        if r.status_code == 200:

            with open(
                filepath,
                "wb"
            ) as f:

                f.write(
                    r.content
                )

            return "ok"


        return "failed"



    except Exception as e:

        return "error"



# ==========================
# MULTI DOWNLOAD
# ==========================


results=[]


with ThreadPoolExecutor(
    max_workers=8
) as executor:


    tasks = [
        executor.submit(
            download_file,
            row
        )
        for _,row in df.iterrows()
    ]


    for task in tqdm(
        as_completed(tasks),
        total=len(tasks)
    ):

        results.append(
            task.result()
        )



print(
    {
        x:results.count(x)
        for x in set(results)
    }
)

  0%|          | 0/174 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
import os

print(
    os.path.exists("Buku_SD_MI")
)

True

In [ ]:
jumlah = 0

for root, dirs, files in os.walk("Buku_SD_MI"):
    for f in files:
        if f.lower().endswith(".pdf"):
            jumlah += 1

print(
    "PDF tersimpan:",
    jumlah
)

PDF tersimpan: 173

In [ ]:
import os
import re


def clean_filename(name):
    name = re.sub(
        r'[\\/*?:"<>|]',
        "",
        name
    )
    return name.strip()



missing = []


for _, row in df.iterrows():

    folder = (
        f"Buku_SD_MI/"
        f"{row['jenis']}/"
        f"Kelas {row['kelas']}"
    )


    filename = clean_filename(
        row["judul"]
    ) + ".pdf"


    filepath = os.path.join(
        folder,
        filename
    )


    if not os.path.exists(filepath):

        missing.append(row)



print(
    "File belum ada:",
    len(missing)
)


for m in missing:

    print(
        m["judul"]
    )

File belum ada: 0

In [ ]:
import os

jumlah = 0
total_size = 0


for root, dirs, files in os.walk("Buku_SD_MI"):

    for f in files:

        if f.lower().endswith(".pdf"):

            jumlah += 1

            total_size += os.path.getsize(
                os.path.join(root,f)
            )


print("Jumlah PDF :", jumlah)

print(
    "Ukuran total:",
    round(
        total_size / 1024 / 1024 / 1024,
        2
    ),
    "GB"
)

Jumlah PDF : 174
Ukuran total: 3.47 GB

In [ ]:
import shutil

shutil.make_archive(
    "Buku_SD_MI_Lengkap",
    "zip",
    "Buku_SD_MI"
)

print("ZIP selesai")

ZIP selesai

In [ ]:
import os

size = os.path.getsize(
    "Buku_SD_MI_Lengkap.zip"
)

print(
    round(size/1024/1024/1024,2),
    "GB"
)

3.06 GB

In [ ]:
from google.colab import files

files.download(
    "Buku_SD_MI_Lengkap.zip"
)

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

In [ ]:
import shutil

shutil.copy(
    "Buku_SD_MI_Lengkap.zip",
    "/content/drive/MyDrive/Buku_SD_MI_Lengkap.zip"
)

'/content/drive/MyDrive/Buku_SD_MI_Lengkap.zip'